name: Run Copyright and License Check
on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  prepare-and-call:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Fetch and decode PR patch
        run: |
          git fetch origin +refs/pull/${{ github.event.pull_request.number }}/merge
          git diff origin/${{ github.event.pull_request.base.ref }}..FETCH_HEAD > pr.patch
          head -n 100 pr.patch
      
      - name: Run copyright/license detector
        uses: targoy-qti/copyright-license-checker-action@main
        with:
          patch_file: pr.patch
          repo_name: ${{ github.repository }}
