name: Run Copyright and license check from PR
 
on:
  pull_request:
    types: [opened, synchronize, reopened]
 
jobs:
  generate-diff:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed to access base commit in all cases
 
      - name: Fetch base branch
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
 
      - name: Generate patch
        run: |
          git diff origin/${{ github.event.pull_request.base.ref }}...HEAD > pr.patch
          echo "Patch generated:"
          head -n 20 pr.patch
 
      - name: Run reusable action
        uses: targoy-qti/copyright-license-checker-action@v1
        with:
          patch_file: pr.patch