name: Run Copyright and license check
 
on:
  pull_request:
    types: [opened, synchronize]
 
jobs:
  prepare-and-call:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch PR patch content
        run: |
          curl -sL ${{ github.event.pull_request.url }}.patch -o pr.patch
          base64 pr.patch > patch.b64
 
      - name: Prepare inputs
        id: inputs
        run: |
          echo "patch_content<<EOF" >> $GITHUB_OUTPUT
          cat patch.b64 >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "repo_name=${{ github.repository }}" >> $GITHUB_OUTPUT
      
      - name: Run copyright/license detector
        uses: targoy-qti/copyright-license-checker-action@main
        with:
          patch_content: ${{ steps.inputs.outputs.patch_content }}
          repo_name: ${{ steps.inputs.outputs.repo_name }}
