name: Run Copyright and License Check
on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  fetch-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR head
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history so we can diff properly
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
 
      - name: Add PR base repo as remote and fetch it
        run: |
          git remote add upstream https://github.com/${{ github.event.pull_request.base.repo.full_name }}.git
          git fetch upstream
 
      - name: Generate final patch between base and head
        run: |
          git diff upstream/${{ github.event.pull_request.base.ref }} > pr.patch
          head -n 100 pr.patch

      - name: Upload patch file
        uses: actions/upload-artifact@v2
        with:
          name: pr-patch
          path: pr.patch

  run-checks:
    runs-on: ubuntu-latest
    needs: fetch-and-run
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Download patch file
        uses: actions/download-artifact@v2
        with:
          name: pr-patch

      - name: Run copyright/license detector
        uses: targoy-qti/copyright-license-checker-action@main
        with:
          patch_file: pr.patch
          repo_name: ${{ github.repository }}
